version: '2'
services:
  ipsec:
    # IMPORTANT!!!! DO NOT CHANGE VERSION ON UPGRADE
    image: rancher/net:holder
    command: sh -c "echo Refer to router sidekick for logs; mkfifo f; exec cat f"
    network_mode: ipsec
    ports:
      - 500:500/udp
      - 4500:4500/udp
    labels:
      io.rancher.sidekicks: router
      io.rancher.scheduler.global: 'true'
      io.rancher.cni.link_mtu_overhead: '0'
      io.rancher.network.macsync: 'true'
      io.rancher.network.arpsync: 'true'
  router:
    cap_add:
      - NET_ADMIN
    image: rancher/net:v0.11.9
    network_mode: container:ipsec
    environment:
      RANCHER_DEBUG: '${RANCHER_DEBUG}'
      IPSEC_REPLAY_WINDOW_SIZE: '${IPSEC_REPLAY_WINDOW_SIZE}'
      IPSEC_IKE_SA_REKEY_INTERVAL: '${IPSEC_IKE_SA_REKEY_INTERVAL}'
      IPSEC_CHILD_SA_REKEY_INTERVAL: '${IPSEC_CHILD_SA_REKEY_INTERVAL}'
    labels:
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent_service.ipsec: 'true'
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
    sysctls:
      net.ipv4.conf.all.send_redirects: '0'
      net.ipv4.conf.default.send_redirects: '0'
      net.ipv4.conf.eth0.send_redirects: '0'
      net.ipv4.xfrm4_gc_thresh: '2147483647'
  cni-driver:
    privileged: true
    image: rancher/net:v0.11.9
    command: sh -c "touch /var/log/rancher-cni.log && exec tail ---disable-inotify -F /var/log/rancher-cni.log"
    network_mode: host
    pid: host
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.network.cni.binary: 'rancher-bridge'
      io.rancher.container.dns: 'true'
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
    network_driver:
      name: Rancher IPsec
      default_network:
        name: ipsec
        host_ports: {{ .Values.HOST_PORTS }}
        subnets:
        - network_address: $SUBNET
        dns:
        - 169.254.169.250
        dns_search:
        - rancher.internal
      cni_config:
        '10-rancher.conf':
          name: rancher-cni-network
          type: rancher-bridge
          bridge: $DOCKER_BRIDGE
          bridgeSubnet: $SUBNET
          logToFile: /var/log/rancher-cni.log
          isDebugLevel: ${RANCHER_DEBUG}
          isDefaultGateway: true
          hostNat: true
          hairpinMode: {{  .Values.RANCHER_HAIRPIN_MODE }}
          promiscMode: {{ .Values.RANCHER_PROMISCUOUS_MODE }}
          mtu: ${MTU}
          linkMTUOverhead: 98
          ipam:
            type: rancher-cni-ipam
            subnetPrefixSize: /{{ .Values.SUBNET_PREFIX }}
            logToFile: /var/log/rancher-cni.log
            isDebugLevel: ${RANCHER_DEBUG}
            routes:
            - dst: 169.254.169.250/32

catalog:
  questions:
  - variable: "DOCKER_BRIDGE"
    label: "Docker Bridge"
    description: "Name of Docker Bridge. Default is `docker0`"
    type: "string"
    default: "docker0"
    required: true
  - variable: MTU
    label: "MTU for the network"
    description: "Adjust the MTU for the network, according to your needs. Ex: GCE(1460), AWS(1500), etc"
    required: true
    default: 1500
    type: int
  - variable: "SUBNET"
    label: "Subnet"
    description: "The subnet to use for the managed IPSEC network."
    type: "string"
    default: '10.42.0.0/16'
    required: true
  - variable: "SUBNET_PREFIX"
    label: "IPAM Subnet Prefix"
    description: "The Subnet prefix to use for the managed network. For most users this is same as the bridge subnet prefix. Ex: 16 if using 10.42.0.0/16 for bridge subnet."
    type: int
    default: 16
    required: true
  - variable: "RANCHER_DEBUG"
    label: "Enable Debug Logs"
    description: "This will enable very verbose debug logs."
    type: "boolean"
    default: "false"
    required: true
  - variable: "RANCHER_HAIRPIN_MODE"
    label: "Enable Hairpin mode"
    description: "If this is enabled, Promiscuous mode needs to be disabled."
    type: "boolean"
    default: "false"
    required: true
  - variable: "RANCHER_PROMISCUOUS_MODE"
    label: "Enable Promiscuous mode on the bridge"
    description: "If this is enabled, Hairpin mode needs to be disabled."
    type: "boolean"
    default: "true"
    required: true
  - variable: "HOST_PORTS"
    label: "Enable Host Ports"
    description: "Flag to enable/disable publishing the ports on the hosts"
    type: "boolean"
    default: "true"
    required: true
  - variable: "IPSEC_REPLAY_WINDOW_SIZE"
    label: "IPSec Replay Window size"
    description: "This option is helpful to adjust the replay window size"
    type: "string"
    default: '1024'
    required: true
  - variable: "IPSEC_IKE_SA_REKEY_INTERVAL"
    label: "IPSec IKE_SA rekey interval"
    description: "Proceed with caution; typical users will not need to change this. Incorrect values can break your Rancher installation."
    type: "string"
    default: '4h'
    required: true
  - variable: "IPSEC_CHILD_SA_REKEY_INTERVAL"
    label: "IPSec CHILD_SA rekey time"
    description: "Proceed with caution; typical users will not need to change this. Incorrect values can break your Rancher installation."
    type: "string"
    default: '1h'
    required: true
